openapi: 3.1.0
info:
  version: v1
  title: activity-service API
  description: activity-service RESTFul api for openapi 3.0 in
  termsOfService: 'https://jumkid.com/terms-of-use'
  contact:
    name: Chooli Yip
    url: jumkid.com
    email: chooli.yip@gmail.com
  license:
    name: Jumkid Public License
    url: 'http://license.jumkid.com'
servers:
  - description: Testing
    url: 'http://test.jumkid.com'
  - description: Live production
    url: 'http://api.jumkid.com'

paths: {}

components:
  schemas:
    CommonResponse:
      description: common response message
      properties:
        success:
          type: boolean
        errorCode:
          type: string
        msg:
          type: string
        data:
          type: object      

    CustomErrorResponse:
      description: custom error response message
      properties:
        timestamp:
          $ref: '#/components/schemas/LocalDateTime'
        message:
          type: string
          nullable: false
        property:
          type: array
        details:
          type: array
        httpCodeMessage:
          type: string

    PagingResponse:
      description: paginated response message
      properties:      
        success:
          type: boolean
        msg:
          type: string
        total:
          type: integer
        size:
          type: integer
        page:
          type: integer      
        data:
          type: array

    LocalDateTime:
      description: local datetime object
      type: string
      pattern: '^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}).(\d{3})'
      example: "2022-06-22T15:47:21.900"

    Month:
      type: string
      enum: [JANUARY, FEBRUARY, MARCH, APRIL, MAY, JUNE, JULY, AUGUST, SEPTEMBER, OCTOBER, NOVEMBER, DECEMBER]
      
    DayOfWeek:
      type: string
      enum: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]

    AccessScope:
      type: string
      enum: [public, private]   